### ISSUE TITLE
[BUG] Unbreakable backpacks

### ISSUE THREAD

**Issue by Pidroxx** [divisionind/BackpacksRemastered#11]
**Bug**
When merging the backpack with an enchanted chestplate,the resulting backpack/chestplate does not lose any durability at all anymore,making it unbreakable.

**To Reproduce**
1. Enchant any chestplate
2. Put it next to a backpack on the crafting grid to merge it
3. Use the resulting item
4. Experience no durability loss at all

**Expected behavior**
This should not happen at all

**Version info**
It happens on craftbukkit and paper 1.15.2

**Comment by drew6017** [comment]
This is actually an intended feature because if the armor were to break, any items stored in the backpack would be lost. 

A means to disable this feature is already in the pipeline, however, I am not sure when this will be released.

**Comment by Pidroxx** [comment]
Oh,thanks for the explanation! Nice work with the plugin though,this was the only problem i had so far.
