### ISSUE TITLE
[BUG] Comment on bukkit

### ISSUE THREAD

**Issue by metzger100** [divisionind/BackpacksRemastered#13]
**Describe the bug**
Dublicate Items with the Enderbag. Someone wrote a comment on bukkit.

**To Reproduce**
Please contact that person who wrote the comment

**Expected behavior**
Not dublicating

**Version info**
Ask the Person

**Comment by drew6017** [comment]
I don't have the time to seek out everyone who may have a found a bug. If the bug is real they can post it here, and I can fix it.
