### ISSUE TITLE
[FEATURE] Add some commands for Admins deactivate/activate specific Backpacks

### ISSUE THREAD

**Issue by metzger100** [divisionind/BackpacksRemastered#14]
**Short description of the feature**
I want to deactivate the Big backpack and the combined Backpack but I can't.

**Additional info, if needed.**
Give more access to Admins.

**Comment by drew6017** [comment]
You can already do this through the use of permissions, see the plugin.yml.

**Comment by Pea85** [comment]
Plugin.yml doesn't show up on the plugins folder. Only the config.yml shows up.
