### ISSUE TITLE
[BUG] Backpack duplication

### ISSUE THREAD

**Issue by guyszabo** [divisionind/BackpacksRemastered#15]
It is possible to make infinite amount of backpacks out of one backpack.

To do that you need to put a backpack in your hand, then press right click on the mouse to equip it like you do with a piece of armor. that results with one backpack on you, and another backpack in your hand.

![2021-02-19_12 36 33](https://user-images.githubusercontent.com/79310830/108494934-cdf30b00-72b0-11eb-814b-fc470afc117b.png)

![2021-02-19_12 36 37](https://user-images.githubusercontent.com/79310830/108494964-d9decd00-72b0-11eb-9553-15c8fd656a67.png)

the version of the plugin is BackpacksRemastered-2020.0.5, and the server is an Aternos server using Spigot 1.16.5

**Comment by drew6017** [comment]
This is only in creative mode and a feature of Minecraft itself. Try it in survival, and it wont work.
