### ISSUE TITLE
[BUG] Backpack storage

### ISSUE THREAD

**Issue by guyszabo** [divisionind/BackpacksRemastered#16]
It is possible to store backpacks in every backpack except in the combined backpack, which you can't put anything in.

![2021-02-19_12 36 04](https://user-images.githubusercontent.com/79310830/108496429-b288ff80-72b2-11eb-8ace-bd3f90e11881.png)

![2021-02-19_12 37 16](https://user-images.githubusercontent.com/79310830/108496439-b583f000-72b2-11eb-930e-eb808f1cee61.png)

the version of the plugin is BackpacksRemastered-2020.0.5, and the server is an Aternos server using Spigot 1.16.5

**Comment by drew6017** [comment]
You store backpacks in the combined backpack by combing it in a crafting grid. It does not store items directly. This is intended.
