### ISSUE TITLE
[BUG] Can't interact with enderchest after opening an ender backpack

### ISSUE THREAD

**Issue by NotBlackyy** [divisionind/BackpacksRemastered#17]
**Describe the bug**
Can't interact with my ender chest, right after I open an ender backpack.

**To Reproduce**
Steps to reproduce the behaviour:
1. Open your ender backpack (I have mine in a combined backpack, this might be important)
2. Close the ender backpack
3. Open your ender chest

**Expected behavior**
You cannot move anything in your inventory, while your ender chest is open.

If I take off my combined backpack, this stops happening. If I put it back on, it continues to happen.

**Version info**
server: craftbukkit 1.16.4

**Additional context**
I do not have admin perms on the server, so I don't know the version of the plugin.

**Comment by drew6017** [comment]
Sorry, I don't know why I never commented, but this was fixed. Thanks for the report!
