### ISSUE TITLE
Combine Backpack [BUG] 

### ISSUE THREAD

**Issue by Zayins** [divisionind/BackpacksRemastered#19]
**Describe the bug**
Players cannot place backpacks into the combine backpack, even though I turn on backpacks.nest. Although I don't want players to put their backpacks in other backpacks (ex: a large backpack)

**To Reproduce**
1. Open a combine backpack.
2. Try to place a combine backpack into combine backpack.
3. Doesn't proceed and puts it straight back into the players inventory

**Expected behavior**
What I expect to happen is that, players can put either a small, large or even an ender backpack into a combine backpack.

**Screenshots**

**Version info**
Spigot 1.16.5

**Comment by drew6017** [comment]
You put backpacks in the combined backpack by combining the desired backpack with the combined backpack in a crafting grid.
