### ISSUE TITLE
More containers for linked backpacks.

### ISSUE THREAD

**Issue by YeetamusBeetamus** [divisionind/BackpacksRemastered#22]
Allow the linked backpack to link to more containers. Currently only links to chests, trapped chests and furnaces which doesn't seem the most useful. If possible could you make it apply to the other containers? Hoppers, barrels, shulker boxes, blast furnace, smokers, dispensers, droppers, brewing stands maybe even lecterns and enchantment tables. Stretch but even minecart chests and hoppers.

Currently it feels the linked backpack isn't the most useful as the other backpacks cover its functions other than maybe sending mail over long distances. Not all are containers are really that useful but I see uses for most of them.

**Comment by drew6017** [comment]
I like it.

**Comment by drew6017** [comment]
I didn't end up doing enchantment tables, anvils, and a few others because they would require more work. However, I might add them later. See 051870f55fe8e421f36f6e294a1c26d333433342.
