### ISSUE TITLE
[FEATURE] customizable colours and armor types

### ISSUE THREAD

**Issue by Yssybyssy** [divisionind/BackpacksRemastered#23]
**Short description of the feature**
Maybe it's possible to add an option, to change the armor type and colours insight the config.yml

recipes:
  small:
    display_name: "&asmall backpack"
    lore:
      - "a small backback"
    ingredients:
      A: IRON_INGOT
      B: LEATHER
      C: GOLD_INGOT
    shape:
      - "BBB"
      - "ACA"
      - "BBB"
    

> colour: #F0F8FF
>     armor_type: iron

**Additional info, if needed.**
More info if applicable. e.g. How this new feature could contribute to game play.

**Comment by drew6017** [comment]
Maybe in the future for the sake of configurability. However, you can combine backpacks with armor/elytra in a crafting grid -- which makes the ability to change this in the config kinda pointless.

**Comment by Chaos02** [comment]
> Maybe in the future for the sake of configurability. However, you can combine backpacks with armor/elytra in a crafting grid -- which makes the ability to change this in the config kinda pointless.

This should be mentioned somewhere accessible, just as how the combined backpack works

**Comment by drew6017** [comment]
@Chaos02 yep

**Comment by drew6017** [comment]
Likely doing this when I roll out the new item manager so I'm going to preemptively close this. Thanks for the suggestion.
