### ISSUE TITLE
[BUG]  backpack inventory "resets" to empty backpack

### ISSUE THREAD

**Issue by xavierbarbary** [divisionind/BackpacksRemastered#24]
**Describe the bug**
a backpack's inventory turns to empty small backpacks inventory when wearing backpack and clicking a linked chest with a backpack key 

**To Reproduce**
1. link a linked backpack to a chest
2. put on backpack
3. click linked chest with back pack key
4. open backpack

**Expected behavior**
nothing changes

**Version info**
backpack version:
    Version: 2021.1.1
    Git Commit: 8bdd12b
    Git Build: 219
    Download Page: https://dev.bukkit.org/projects/backpack-item

spigot version 1.17.1

full version command output:
    This server is running CraftBukkit version 3258-Spigot-dc75aca-960f310 (MC: 1.17.1) (Implementing API version 1.17.1-R0.1-SNAPSHOT)
    You are running the latest version

**Additional context**
works with small and large backpack deletes all items in backpack

**Comment by drew6017** [comment]
"2. put on backpack" wut? ma dude. you click the chest while holding the backpack in your hand to link it. then you put it on. then you hold bp key, then you use key and it opens the backpack.

**Comment by xavierbarbary** [comment]
@drew6017
sorry i was unclear there i meant a normal small or large backpack
and i did slightly more testing:

1  link linked backpack to chest
2 put on linked backpack
3 open linked backpack
4 put on normal backpack(small or large)
5 click on linked chest
6 open normal backpack

a demonstration
[examle.zip](https://github.com/divisionind/BackpacksRemastered/files/7358345/examle.zip)
