### ISSUE TITLE
[BUG] trying to open the large backpack but the ender backpack opens instead.

### ISSUE THREAD

**Issue by aerdep** [divisionind/BackpacksRemastered#25]
**Describe the bug**
ive been using ender and large backpack all together for the past few days, but then a bug occurred. i tried opening the large backpack but the ender backpack opens.

**Expected behavior**
being able to use both backpacks without having the issue listed

**Screenshots**
![2021-10-17_13 39 24](https://user-images.githubusercontent.com/92685122/137636754-4e6542f2-2ab2-4ef4-80b0-01abea393f91.png)

![2021-10-17_13 39 27](https://user-images.githubusercontent.com/92685122/137636758-6af00038-97e4-4b2f-8b7e-5b7f04bb6db3.png)

**Version info**
plugin bukkit 1.17.1 server 1.17.1

**Comment by drew6017** [comment]
Connected to #28. See that issue for updates. Thanks for the report.
