### ISSUE TITLE
Theres a dupe glitch [BUG] 

### ISSUE THREAD

**Issue by DarkWolfZachary** [divisionind/BackpacksRemastered#28]
[Dupe video](https://www.youtube.com/watch?v=tQ2Gf5V_TsI)

**Comment by Lightwere** [comment]
> [Dupe video](https://www.youtube.com/watch?v=tQ2Gf5V_TsI)

No there isn't dupe glitch, it's Rick roll with different link

**Comment by aarushtools** [comment]
shut the fuck up skid @DarkWolfZachary

**Comment by tristanzwart** [comment]
Shut up it is just a rickroll

**Comment by DarkWolfZachary** [comment]
It's not a rick roll, I'd you don't trust the link go to super troopers channel, it's the most recent video

**Comment by drew6017** [comment]
Thanks for the report. I am working on it now and should have a fix by tomorrow.

**Comment by DarkWolfZachary** [comment]
> Thanks for the report. I am working on it now and should have a fix by tomorrow.

Thank you! Also thanks for not thinking its a rick roll lol.

**Comment by drew6017** [comment]
Lol yea, I try to take dup glitches pretty seriously. Fixed in 2022.1.1, should be out as soon as bukkit approves the update.

**Comment by DarkWolfZachary** [comment]
Ok
