### ISSUE TITLE
[FEATURE] Make the plugin.yml file available in the plugins folder on the server.

### ISSUE THREAD

**Issue by Pea85** [divisionind/BackpacksRemastered#33]
**Short description of the feature**
I want to be able to change the permissions for the backpacks and enable/disable backpacks. I was redirected to a plugins.yml file on the github for this. But the file isn't available on the plugins folder on the server files after installation. 
**Additional info, if needed.**
Please make the plugins.yml available for us to change permissions and enable/disable certain backpacks
![Screenshot_20220620-113248_Chrome](https://user-images.githubusercontent.com/107832507/174535645-983c47c2-198d-4c06-bb08-bfe4cfbdd76a.jpg)

**Comment by drew6017** [comment]
Well, the plugin.yml is just a list of permissions that Backpacks handles for the server + descriptions. This is so server admins can use any permission management plugin they would like to have per-user control over features (more flexible).

They are all pretty much the same, a lot of people like `PermissionsEx`.
