### ISSUE TITLE
[BUG] Backpacks can be put into Backpacks but not into the combined backpack.

### ISSUE THREAD

**Issue by Chaos02** [divisionind/BackpacksRemastered#34]
It appears that you can (is this intentional?) nest backpacks into other backpacks, which makes for unlimited storage.
If this is intended, there should be an option to disable it.
Otherwise, the backpack recognition seems to be broken, as you can't put backpacks into the combined backpack but any other backpacks.
Infact, you cannot pick up *any* items when inside the combined backpack GUI

**Comment by Xbox-360-1063** [comment]
Same issue here

**Comment by longwolfdude** [comment]
To put backpacks in the combined backpack you combine it in the crafting grid. Then if you want, do /bm split to remove the backpack from the combined backpack.

**Comment by Chaos02** [comment]
thanks, that still doesn't solve the nested backpacks tho!

**Comment by drew6017** [comment]
the `backpacks.nest` permission is what you are looking for, see [plugin.yml](https://github.com/divisionind/BackpacksRemastered/blob/master/src/main/resources/plugin.yml)
