### ISSUE TITLE
Upgrading a diamond chestplate with bags to netherite breaks it

### ISSUE THREAD

**Issue by Zarius1337** [divisionind/BackpacksRemastered#38]
Upgrading a diamond chestplate with bags to netherite breaks it

**To Reproduce**
Upgrade a diamond chestplate that has backpacks attached to it, to netherite

To use the backpack key to open it and have it operate normally

Additionally, when I went to split the backpack, it says the item is not a bag

**Comment by drew6017** [comment]
Gotcha, I'll fix it when I get a chance.

I've been meaning to add a backpack history feature as well considering a lot of these version-change related bugs tend to be the result of new "item transformers" not persisting the backpack nbt data; resulting in a loss of items, which sucks.

At least this way an admin could restore backpacks that were lost via commands.

**Comment by Zarius1337** [comment]
Hey thanks for the reply! Yeah that would be a fantastic idea!
Been loving the mod tho!

**Comment by drew6017** [comment]
You're good to go.
