### ISSUE TITLE
[BUG] If you try to open an unlinked backpack in a combined backpack it stops working

### ISSUE THREAD

**Issue by deprecatedbrain** [divisionind/BackpacksRemastered#40]
**Describe the bug**
If you have an unlinked backpack in a combined backpack the plugin stop working for you. Even after relogging. It still works for other players. It goes back to normal after restarting the server.

**To Reproduce**
1. Create an unlinked backpack and put it in a combined backpack
2. Try to open it.

**Expected behavior**
Its expected to either give a warning, or do nothing at all.

**Version info**
Backpacks 2022.1.7 Paper 1.19.2 #270

**Additional context**
No errors are shown in the console.

**Comment by drew6017** [comment]
Thanks for the report!
