### ISSUE TITLE
[BUG] Furnace Backpack cannot be opened (v2022.1.6)

### ISSUE THREAD

**Issue by RawlsRawley** [divisionind/BackpacksRemastered#43]
**Describe the bug**
Even though trying different backpack keys, the furnace backpack cannot be opened when equipped (thus at all, obviously)

**To Reproduce**
1. Equip furnace backpack
2. Take backpack key into your hand
3. Rightclick
4. Notice that there is no prompt/UI showing

**Expected behavior**
What should happen (intuitively) is the backpack UI of the furnace backpack opening up to store items.

**Version info**
Spigot: 1.19.2

**Comment by drew6017** [comment]
### BackpacksRemastered-2022.1.7
* fix furnace backpack bug in 1.19
