### ISSUE TITLE
[BUG] Large backpacks turn into linked chest/enderchest and unable to fix

### ISSUE THREAD

**Issue by Thugne** [divisionind/BackpacksRemastered#6]
I had a large backpack full of my stuff 
I link a separate backpack to a chest, I go and put the large backpack on to put other bp inside, chests gets fucked. just got the plugin so it's not a huge hassle as All I had in there was the other backpacks but still kinda annoying.
![bp](https://user-images.githubusercontent.com/61918193/76151033-2f25cc80-60a8-11ea-8404-279ed35550da.png)

**Comment by drew6017** [comment]
Not enough information. Please follow the bug reporting format and describe the exact process.
