### ISSUE TITLE
[FEATURE] Please Make This Plugin Support Anti Grief Chest

### ISSUE THREAD

**Issue by aldiz1711** [divisionind/BackpacksRemastered#7]
I Using GriefPrevention Anti-Grief Plugin, But Linked Backpack can open another player chest

**Comment by drew6017** [comment]
Can you provide a link to the actual plugin page?

**Comment by drew6017** [comment]
I just assumed this was the one you were talking about (https://dev.bukkit.org/projects/grief-prevention). Added as of 2020.0.4.
