### ISSUE TITLE
[BUG] Cannot create keys or backpacks on a paper server

### ISSUE THREAD

**Issue by Earl-Brown** [divisionind/BackpacksRemastered#8]
**Describe the bug**
I have collected the materials to create a key and a small or large backpack, but when I attempt to create them at the crafting table, nothing happens.

**To Reproduce**
Lay out the materials as described on the plugin page
Nothing is created in the crafted item box
Attempting to "grab" from the crafted item box does nothing

**Expected behavior**
A backpack or a key should be presented as a crafted item.

**Version info**
Server: git-Paper-208 (MC: 1.15.2)
BackpacksRemastered: 2020.0.4

**Comment by drew6017** [comment]
You probably changed the recipe in the config. If so, you need to use that one.

**Comment by Earl-Brown** [comment]
I made no configuration changes.  But I've shifted to a bedrock server, so it's not a concern for me any more.
